version: '2' 

services:

  mysql:

    image: mysql

    container_name: mysql-spring

    environment:

      - MYSQL_ROOT_PASSWORD=1234

      - MYSQL_DATABASE=test

    #restart: always

    networks:

      - spring_mysql_network
 

  spring-repository:

    depends_on:

      - mysql

    image: scgvk/springbackend:latest

    container_name: springbackend

    ports:

      - 8443:8443

    links:

      - mysql:mysql

    #restart: always

    networks:

      - spring_mysql_network

    environment:

      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test



networks:

  spring_mysql_network:

driver: bridge
